export const emptyFilters = {
  city: "",
  zip_code: "",
  department: "",
  price_min: "",
  price_max: "",
  surface_min: "",
  surface_max: "",
  type_bien: "",
  score_min: "",
  source_site: "",
  enrichment_status: "",
  zonage: "",
  sort: "score",
  direction: "desc",
};
